### ISSUE TITLE
Import problem

### ISSUE THREAD

**Issue by BDonnot** [jhmenke/grid2op_pp_baseline#3]
Hello,

Sorry to bother you again, but it seems your baseline is not working.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/benjamin/Documents/l2rpn-baselines/l2rpn_baselines/PandapowerOPFAgent/__init__.py", line 6, in <module>
    from l2rpn_baselines.PandapowerOPFAgent.PandapowerOPFAgent import PandapowerOPFAgent
  File "/home/benjamin/Documents/l2rpn-baselines/l2rpn_baselines/PandapowerOPFAgent/PandapowerOPFAgent.py", line 9, in <module>
    from grid2op.Agent import Agent
ImportError: cannot import name 'Agent' from 'grid2op.Agent' (/home/benjamin/Documents/grid2op/grid2op/Agent/__init__.py)
```

Indeed now the class Agent is called BaseAgent in grid2op.

Benjamin

**Comment by jhmenke** [comment]
Sorry, i thought i had fixed that already, but i guess only on my local machine. I'm out of office for the rest of the week but will try to correct this in between or Monday at the latest.

**Comment by jhmenke** [comment]
Indeed i had fixed it but not commited. Should be updated now.
